/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.PetSchoolStaffRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.PetTrainingSchoolOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.JoinPetSchoolRequest;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chaitanya
 */
public class PetSchoolStaffWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PetSchoolStaffWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private PetTrainingSchoolOrganization petTrainingSchoolOrganization;
    private EcoSystem business;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public PetSchoolStaffWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, PetTrainingSchoolOrganization petTrainingSchoolOrganization, Enterprise enterprise, EcoSystem business) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.petTrainingSchoolOrganization = petTrainingSchoolOrganization;
        this.enterprise = enterprise;
        this.business = business;
        populateAdmissionReq();
        
    }
   
    
    public void populateAdmissionReq(){
                DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();

        model.setRowCount(0);
                enterprise.getWorkQueue().getWorkRequestList()
                        .stream().filter(wq -> wq instanceof JoinPetSchoolRequest)
                        .forEach(request -> {
                            Object[] row = new Object[12];
                            row[0] =((JoinPetSchoolRequest) request);
                            row[1] = ((JoinPetSchoolRequest) request).getUsername();
                            row[2] = request.getStatus();
                            row[3] = ((JoinPetSchoolRequest) request).getCourseType();

                            row[4] = ((JoinPetSchoolRequest) request).getRequestDate();
                            row[5] = ((JoinPetSchoolRequest) request).getResolveDate();
                            row[6] = ((JoinPetSchoolRequest) request).getComments();
                            model.addRow(row);
                        });
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshTestJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        reqApprovalBtn = new javax.swing.JButton();
        rejectBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 850));
        setSize(new java.awt.Dimension(1200, 850));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refreshTestJButton.setBackground(new java.awt.Color(0, 153, 255));
        refreshTestJButton.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });
        add(refreshTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 40, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 28, 150, 30));

        valueLabel.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(226, 153, 0));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 158, 26));

        workRequestJTable.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RequestId", "Request Raised By", "Status", "Course Type", "Request Date", "Resolve Date", "Comments"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 1100, 300));

        reqApprovalBtn.setBackground(new java.awt.Color(0, 153, 255));
        reqApprovalBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        reqApprovalBtn.setText("Approve");
        reqApprovalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqApprovalBtnActionPerformed(evt);
            }
        });
        add(reqApprovalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 410, 108, 45));

        rejectBtn.setBackground(new java.awt.Color(0, 153, 255));
        rejectBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        rejectBtn.setText("Reject");
        rejectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectBtnActionPerformed(evt);
            }
        });
        add(rejectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, 105, 45));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/output-onlinegiftools.gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 200, 35));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/adopt_1200x850.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed
        //populateAdmissionReq();
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void reqApprovalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqApprovalBtnActionPerformed
        // TODO add your handling code here:
        Integer selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow >= 0) {
            JoinPetSchoolRequest pa = (JoinPetSchoolRequest) workRequestJTable.getValueAt(selectedRow, 0);
            if(pa.getStatus().equalsIgnoreCase("Approved") || pa.getStatus().equalsIgnoreCase("Request Rejected")){
                JOptionPane.showMessageDialog(null, "request already processed");
                return;
            }
            pa.setStatus("Approved");
            pa.setReceiver(userAccount);
            pa.setResolveDate(new Date());
            Map a = new HashMap<String, String>();
            a.put("Approval Comment", "Congratulations and thankyou for joining the pet training School!");
            pa.setComments1(a);
            JOptionPane.showMessageDialog(null, "Congratulations and thankyou for joining the pet training School!");
            dB4OUtil.storeSystem(business);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from Requests Available for approval");
        }
    }//GEN-LAST:event_reqApprovalBtnActionPerformed

    private void rejectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectBtnActionPerformed
        // TODO add your handling code here:
        Integer selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow >= 0) {
            JoinPetSchoolRequest pa = (JoinPetSchoolRequest) workRequestJTable.getValueAt(selectedRow, 0);
            if(pa.getStatus().equalsIgnoreCase("Request Rejected") || pa.getStatus().equalsIgnoreCase("Approved request")){
                JOptionPane.showMessageDialog(null, "request already processed");
                return;
            }
            pa.setStatus("Request Rejected");
            pa.getPet().setIsAvailableForAdoption(Boolean.TRUE);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from request table!!");
        }
    }//GEN-LAST:event_rejectBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton rejectBtn;
    private javax.swing.JButton reqApprovalBtn;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
