/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.UserRole;

import Business.WorkQueue.JoinPetSchoolRequest;
import Business.WorkQueue.ReportStrayAnimalRequest;
import Business.DB4OUtil.DB4OUtil;
import Business.POJO.Users;
import Business.EcoSystem;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Network.Network;
import Business.Regex.Vald;
import Business.WorkQueue.ReportStrayAnimalRequest;
import com.teamdev.jxbrowser.browser.Browser;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.io.IOException;
import java.net.MalformedURLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import javax.swing.event.MouseInputListener;
import org.apache.commons.httpclient.URIException;
import org.apache.log4j.Logger;
import org.jxmapviewer.OSMTileFactoryInfo;
import org.jxmapviewer.input.PanMouseInputListener;
import org.jxmapviewer.input.ZoomMouseWheelListenerCenter;
import org.jxmapviewer.viewer.DefaultTileFactory;
import org.jxmapviewer.viewer.GeoPosition;
/**
 *
 * @author chaitanya
 */
public class JoinPetSchoolReuqestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form JoinPetSchoolReuqestJPanel
     */
    
    private JPanel userProcessContainer;
    private Users users;
    private EcoSystem business;
    private Network currNetwork;

    private Vald vald= Vald.getInstance();
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private final Logger logger = Logger.getLogger(this.getClass());
    public JoinPetSchoolReuqestJPanel(JPanel userProcessContainer, Users users, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.users = users;
        this.business = business;
        business.getIdGenInstance().getReqId();
        reportIDTextField.setText(String.valueOf(business.getIdGenInstance().getReqId()));
        populateComboBox();     
        logger.info(users.getName() + " logged into Report Animal Panel");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        reportIDTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentsTextArea = new javax.swing.JTextArea();
        CourseTypeComboBox = new javax.swing.JComboBox<>();
        submitReportBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        animalTypeComboBox = new javax.swing.JComboBox<>();
        backJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cityComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1147, 809));
        setSize(new java.awt.Dimension(1147, 809));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("Join Pet School");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, 40));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setText("Report ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setText("Course type:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel9.setText("Comments:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, -1, 40));

        reportIDTextField.setEditable(false);
        reportIDTextField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        reportIDTextField.setEnabled(false);
        reportIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportIDTextFieldActionPerformed(evt);
            }
        });
        add(reportIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 202, -1));

        commentsTextArea.setColumns(20);
        commentsTextArea.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        commentsTextArea.setRows(5);
        jScrollPane1.setViewportView(commentsTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 230, 180));

        CourseTypeComboBox.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        CourseTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Basic Training", "Agility Training" }));
        CourseTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseTypeComboBoxActionPerformed(evt);
            }
        });
        add(CourseTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 202, -1));

        submitReportBtn.setBackground(new java.awt.Color(0, 153, 255));
        submitReportBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        submitReportBtn.setText("Submit");
        submitReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitReportBtnActionPerformed(evt);
            }
        });
        add(submitReportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, 108, 40));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setText("Animal Type: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        animalTypeComboBox.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        animalTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select---", "Cat", "Dog" }));
        add(animalTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 202, -1));

        backJButton.setBackground(new java.awt.Color(0, 153, 255));
        backJButton.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 40));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setText("City:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        cityComboBox.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityComboBoxActionPerformed(evt);
            }
        });
        add(cityComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 202, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/school.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 810));
    }// </editor-fold>//GEN-END:initComponents

    private void reportIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportIDTextFieldActionPerformed

    private void submitReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitReportBtnActionPerformed
        // TODO add your handling code here:
        JoinPetSchoolRequest report = new JoinPetSchoolRequest();
        try{
           
                report.setReportId(reportIDTextField.getText());
                
                report.setComments(commentsTextArea.getText());
                report.setSender(users);
                report.setAnimalType(animalTypeComboBox.getSelectedItem().toString());
                report.setCourseType(CourseTypeComboBox.getSelectedItem().toString());
                report.setStatus("New Request");
                report.setUsername(users.getName());
                dB4OUtil.storeSystem(business);
                //System.out.println(network.ge);
                business.getNetworkList().stream().filter((network) -> (network.getName().equalsIgnoreCase(cityComboBox.getSelectedItem().toString()))).map((network) -> {
                    currNetwork = network;
                    return network;
                }).forEachOrdered((_item) -> {
                    currNetwork.getEnterpriseDirectory().getEnterpriseList().stream().filter((e) -> (e.getEnterpriseType().equals(EnterpriseType.PetSchool))).forEachOrdered((e) -> {
                        e.getWorkQueue().getWorkRequestList().add(report);
                    });
                });
                users.getWorkQueue().getWorkRequestList().add(report);
                JOptionPane.showMessageDialog(null, "Successfull");
                logger.info(users.getName() + " sent reuquest for addmission with reportID" + reportIDTextField.getText());
                userProcessContainer.remove(this);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.previous(userProcessContainer);
            }
            
        
        catch(RuntimeException run){
            JOptionPane.showMessageDialog(null, "Invalid input in zipcode");
            logger.error(users.getName() + " Invalid input in zipcode");

        }
    }//GEN-LAST:event_submitReportBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void cityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cityComboBoxActionPerformed

    private void CourseTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseTypeComboBoxActionPerformed
        // TODO add your handling code here:
               
                
                

    }//GEN-LAST:event_CourseTypeComboBoxActionPerformed
    
    private void populateComboBox() {
        cityComboBox.removeAllItems();
        for (Network n: business.getNetworkList()) {
                cityComboBox.addItem(n.getName());
            }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CourseTypeComboBox;
    private javax.swing.JComboBox<String> animalTypeComboBox;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox<String> cityComboBox;
    private javax.swing.JTextArea commentsTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField reportIDTextField;
    private javax.swing.JButton submitReportBtn;
    // End of variables declaration//GEN-END:variables
}
