/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Organization.Organization;
import Business.Organization.Organization.MerchantType;
import Business.Organization.Organization.NGOType;
import Business.Organization.Organization.PetSchoolType;
import Business.Organization.Organization.VetHospitalType;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shree
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    private OrganizationDirectory directory;
    private Enterprise enterprise;
    private JPanel userProcessContainer;
//    private String enterpriseType;
    private final EnterpriseType enterpriseType;
    EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationJPanel(JPanel userProcessContainer, OrganizationDirectory organizationDirectory,Enterprise enterprise, EnterpriseType enterpriseType, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.directory = organizationDirectory;
        this.enterpriseType = enterpriseType;
        this.system = system;
        this.enterprise = enterprise;
        jLabel2.setText(enterpriseType.getValue());
        populateTable();
        populateCombo();
    }

    private void populateCombo(){
        organizationJComboBox.removeAllItems();
        
        String changetype = enterpriseType.getValue();
        if(changetype.equalsIgnoreCase("Vet Hospital Enterprise")){
            for(VetHospitalType type:Organization.VetHospitalType.values()){
                 if (!type.getValue().equals(VetHospitalType.Admin.getValue()))
                    organizationJComboBox.addItem(type);
            }
        }
        if(changetype.equalsIgnoreCase("Merchant Enterprise")){
            for(MerchantType type:Organization.MerchantType.values()){
                 if (!type.getValue().equals(MerchantType.Admin.getValue()))
                    organizationJComboBox.addItem(type);
            }
        }
        if(changetype.equalsIgnoreCase("NGO Enterprise")){
            for(NGOType type:Organization.NGOType.values()){
                 if (!type.getValue().equals(NGOType.Admin.getValue()))
                    organizationJComboBox.addItem(type);
            }
        }
        
        if(changetype.equalsIgnoreCase("Pet Training School Enterprise")){
            for(PetSchoolType type:Organization.PetSchoolType.values()){
                 if (!type.getValue().equals(PetSchoolType.Admin.getValue()))
                    organizationJComboBox.addItem(type);
            }
        }
       
        organizationJComboBox.setSelectedIndex(-1);
    }

    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();
        
        model.setRowCount(0);
        
        for (Organization organization : directory.getOrganizationList()){
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization;
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addJButton = new javax.swing.JButton();
        organizationJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        BtnDelete = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnEdit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setSize(new java.awt.Dimension(1200, 850));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        organizationJTable.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        organizationJTable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(organizationJTable);
        if (organizationJTable.getColumnModel().getColumnCount() > 0) {
            organizationJTable.getColumnModel().getColumn(0).setResizable(false);
            organizationJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 810, 140));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 420, -1));

        backJButton.setBackground(new java.awt.Color(0, 153, 255));
        backJButton.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.setToolTipText("");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 40));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("Organization Type ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, 30));

        addJButton.setBackground(new java.awt.Color(0, 153, 255));
        addJButton.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        addJButton.setText("Add Organization");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 200, 40));

        organizationJComboBox.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(organizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 160, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("Organization Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, 30));

        jTextField1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 160, -1));

        BtnDelete.setBackground(new java.awt.Color(0, 153, 255));
        BtnDelete.setText("Delete Organization");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(BtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 240, -1, -1));

        BtnUpdate.setBackground(new java.awt.Color(0, 153, 255));
        BtnUpdate.setText("Update Organzation");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(BtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, -1, -1));

        BtnEdit.setBackground(new java.awt.Color(0, 153, 255));
        BtnEdit.setText("Edit");
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/adopt_1200x850.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 850));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        if(jTextField1.getText().isEmpty() || organizationJComboBox.getSelectedItem()==null){
             JOptionPane.showMessageDialog(null, "Please enter the details of organization!");
             addJButton.setEnabled(false);
             return;
        }
        if(checkIfOrgIsUnique(jTextField1.getText())){
            if(enterpriseType.getValue().equalsIgnoreCase("Vet Hospital Enterprise")){
                VetHospitalType type = (VetHospitalType) organizationJComboBox.getSelectedItem();
                directory.createOrganizationHospital(type,jTextField1.getText());
            }
            if(enterpriseType.getValue().equalsIgnoreCase("Merchant Enterprise")){
                MerchantType type = (MerchantType) organizationJComboBox.getSelectedItem();
                directory.createOrganizationSupplier(type,jTextField1.getText());
            }
            if(enterpriseType.getValue().equalsIgnoreCase("NGO Enterprise")){
                NGOType type = (NGOType) organizationJComboBox.getSelectedItem();
                directory.createOrganizationNgo(type,jTextField1.getText());
            }
            
            if(enterpriseType.getValue().equalsIgnoreCase("Pet Training School Enterprise")){
                PetSchoolType type = (PetSchoolType) organizationJComboBox.getSelectedItem();
                directory.createOrganizationPetSchool(type,jTextField1.getText());
            }
            
             dB4OUtil.storeSystem(system);
            populateTable();
            jTextField1.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null, "Please enter unique details! Organisation already exists");
        }
    }//GEN-LAST:event_addJButtonActionPerformed

    public Boolean checkIfOrgIsUnique(String name){
        return directory.getOrganizationList().stream().noneMatch(org->org.getName().equalsIgnoreCase(name));
    }
    
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        addJButton.setEnabled(true);
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationJComboBoxActionPerformed
    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();
        int selectedRow = organizationJTable.getSelectedRow();
        if (selectedRow >= 0) {
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete?", "Warning", selectionButton);
            if (selectionResult == JOptionPane.YES_OPTION) {
            Organization organization  = (Organization) organizationJTable.getValueAt(selectedRow, 1);           
            System.out.println(organization);
            System.out.println(enterprise);
                     
            enterprise.getOrganizationDirectory().removeOrganization(organization);
            populateTable();
            }
        }else{
               JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
        
        String name = jTextField1.getText();
         
         //Employee employee = (Employee) organizationEmpJComboBox.getSelectedItem();


         
       
            Organization org = (Organization) organizationJComboBox.getSelectedItem();
            DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();
            int selectedRow = organizationJTable.getSelectedRow();
            if (selectedRow >= 0) {
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to update?", "Warning", selectionButton);
            if (selectionResult == JOptionPane.YES_OPTION) {
                Organization organization  = (Organization) organizationJTable.getValueAt(selectedRow, 1);
                System.out.println(organization);

                organization.setName(name);
                BtnUpdate.setEnabled(false);
                addJButton.setEnabled(true);
                jTextField1.setText("");
               populateTable();

                JOptionPane.showMessageDialog(null, "update success");
            }
            
            else {
            JOptionPane.showMessageDialog(null, "Please select a row");
            
        }
            }
         
    }//GEN-LAST:event_BtnUpdateActionPerformed
Organization selectedOrganization;

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        // TODO add your handling code here:
        
        int selected = organizationJTable.getSelectedRow();
        if(selected < 0){
            JOptionPane.showMessageDialog(null, "please select a row");
        }else{
            BtnUpdate.setEnabled(true);
            addJButton.setEnabled(false);
            selectedOrganization = (Organization)organizationJTable.getValueAt(selected, 1);
            organizationJComboBox.setSelectedItem(organizationJComboBox.getSelectedItem());
            organizationJComboBox.setEnabled(false);
            jTextField1.setText(selectedOrganization.getName());
            
            BtnUpdate.setEnabled(true);
        }
    }//GEN-LAST:event_BtnEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JTable organizationJTable;
    // End of variables declaration//GEN-END:variables
}
