/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NgoStaffRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.NgoOfficeOrganization;
import Business.Organization.Organization;
import Business.Organization.PetShelterOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.UserRole.ReportAnimalJPanel;

/**
 *
 * @author chaitanya
 */
public class NgoStaffWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private NgoOfficeOrganization ngoOfficeOrganization; 
    private Enterprise enterprise;
    private EcoSystem business;
    
    /**
     * Creates new form NgoStaffWorkAreaJPanel
     */
    public NgoStaffWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, NgoOfficeOrganization ngoOfficeOrganization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        valueLabel.setText(enterprise.getName());
        this.userProcessContainer = userProcessContainer;
        this.ngoOfficeOrganization = ngoOfficeOrganization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewAllRequestsBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(224, 226, 249));
        setPreferredSize(new java.awt.Dimension(1200, 850));
        setSize(new java.awt.Dimension(1200, 850));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setText("NGO Staff Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        viewAllRequestsBtn.setBackground(new java.awt.Color(0, 153, 255));
        viewAllRequestsBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        viewAllRequestsBtn.setText("View All Requests");
        viewAllRequestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllRequestsBtnActionPerformed(evt);
            }
        });
        add(viewAllRequestsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 200, 60));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton1.setText("View Supply Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, 60));

        enterpriseLabel.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 150, 30));

        valueLabel.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(226, 153, 0));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 440, 26));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/NGOStaff.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 644, 400));

        jLabel3.setBackground(new java.awt.Color(224, 226, 249));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void viewAllRequestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllRequestsBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ViewRequestJPanel ", new ViewRequestJPanel(userProcessContainer, userAccount, ngoOfficeOrganization , enterprise, business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewAllRequestsBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Organization org = null;
        for (Organization organization1 : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization1 instanceof PetShelterOrganization){
                org = organization1;
                break;
            }
        }
        if (org!=null){
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("SupplyRequestJPanel ", new SupplyRequestJPanel(userProcessContainer, userAccount, ngoOfficeOrganization, (PetShelterOrganization) org, enterprise, business));
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JButton viewAllRequestsBtn;
    // End of variables declaration//GEN-END:variables
}
